text_jugador_adicionado = 'Jugador adicionado exitosamente.... :)'
text_listar_todos_los_jugadores = 'Todos los Jugadores con estado: '
ID_ = 'ID #: '
text_opcion_seleccionar = 'Que desea hacer?, Seleccionar una opcion:'
text_adicionar_jugador = 'Adicionar Nuevo Jugador y agregar automaticamente a la partida'
text_buscar_otro_jugador = 'Buscar otro jugador'
text_mostrar_jugador_estado = 'Mostrar todos los jugadores: '
text_salir_busqueda = 'Salir de Busqueda'
text_anular_partida = 'Anular Partida y Salir de Busqueda'
text_listar_jugador_estado = 'Todos los Jugadores con estado: '
text_adicionado_a_partida = 'jugador adicionado a una nueva partida.... '
text_jugador_encontrado = 'El jugador has sido encontrado! '
text_introducir_correo = 'Ingresar correo electronico del jugador: '
text_introducir_correo_adversario = 'Ingresar correo electronico del jugador adversario: '
text_salir_menu = 'Saliendo de este menu....'
text_nombre_partida= 'Ingresar nombre de la partida:'
text_jugador_gano_partidas = 'El jugador ya gano partidas :)'
text_jugador_en_partida = 'El jugador esta en una partida...'
text_nombres_repetidos = '''Nombres Repetidos!
No puedes autoasignarte una partida
Intenta Nuevamente!!'''

text_buscar_otra_partida = 'Buscar otra partida'
text_mostrar_partidas_activas = 'todas las partidas con estado: '
text_partida_no_encontrada = 'No se ha encontrado la partida en el grupo de partidas con estado activo :('
text_definir_ganador = 'Hora de elegir al ganador ------------------'
text_confirmar_para_finalizar = 'Esta seguro de finalizar la partida?'
text_opcion_ganador = 'Introduzca 1 o 2 para seleccionarlo: '

text_sin_jug_activos = 'No hay jugadores registrados aun, adicione un nuevo jugador'
text_sin_jug_gandores = 'No hay jugadores ganadores aun, finalize una partida'